# Puerto donde correrá tu página web
server.port=8081
spring.application.name=test

# Configuración de conexión a la base de datos XAMPP (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/cine
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (Crea/Actualiza las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactiva la página de error blanca por defecto de Spring
server.error.whitelabel.enabled=false


# Tiempo máximo de inactividad antes de cerrar la sesión automáticamente (ej: 15 minutos)
server.servlet.session.timeout=15m

# Forzar a que las cookies de sesión solo se transmitan por HTTP (evita robo por JavaScript)
server.servlet.session.cookie.http-only=true